apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: floracore-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: floracore-db-deployment
spec:
  selector:
    matchLabels:
      app: floracore-db
  template:
    metadata:
      labels:
        app: floracore-db
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: floracore_db
        - name: POSTGRES_USER
          value: flora_user
        - name: POSTGRES_PASSWORD
          value: flora_password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: floracore-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: floracore-db-service
spec:
  selector:
    app: floracore-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
