apiVersion: v1
kind: Secret
metadata:
  name: floracore-secrets
  namespace: default
type: Opaque
stringData:
  # LƯU Ý: KHÔNG commit file này (nếu chứa mật khẩu thật) lên GitHub public!
  # Đã trỏ vào Service floracore-db-service nội bộ của K8s
  ConnectionStrings__DefaultConnection: "Host=floracore-db-service;Database=floracore_db;Username=flora_user;Password=flora_password;Port=5432"
  ConnectionStrings__Redis: "floracore-redis-service:6379"
  Jwt__Secret: "your-super-secret-jwt-key-at-least-32-chars-long"
