apiVersion: v1
kind: Secret
metadata:
  name: blogapi-secrets
  namespace: default
type: Opaque
stringData:
  # LƯU Ý: KHÔNG commit file này (nếu chứa mật khẩu thật) lên GitHub public!
  # Đã trỏ vào Service blog-db-service nội bộ của K8s
  ConnectionStrings__DefaultConnection: "Host=blog-db-service;Database=blog_db;Username=db_user;Password=db_password;Port=5432"
  Jwt__Secret: "your-super-secret-jwt-key-at-least-32-chars-long"
